apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dogecoin.fullname" . }}-config
  namespace: {{ .Values.namespace | default "default" }}
data:
  dogecoin.conf: |
    {{- range $key, $val := .Values.dogecoinConf }}
    {{- if eq $key "rpcallowip" }}
    {{- range $val }}
    {{ $key }}={{ . }}
    {{- end }}
    {{- else }}
    {{ $key }}={{ $val }}
    {{- end }}
    {{- end }}