apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dogecoin.fullname" . }}-rpc-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  rpcpassword: {{ .Values.rpcPassword | b64enc | quote }}
