apiVersion: v1
kind: Secret
metadata:
  name: dogecoin-rpc-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep  # Prevents Helm from updating/deleting
type: Opaque
data:
  rpcpassword: {{ .Values.rpcPassword | b64enc | quote }}
