apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogecoin.fullname" . }}
  labels:
    {{- include "dogecoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: dogecoind
      port: {{ .Values.service.port }}
      targetPort: dogecoind  # Matches Deployment's named port
      protocol: TCP
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc  # Matches Deployment's named port
      protocol: TCP
  selector:
    {{- include "dogecoin.selectorLabels" . | nindent 4 }}