# This is a storage class needed for the pvc on AWS EBS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immediate-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: Immediate
